apiVersion: apps/v1
kind: Deployment
metadata:
{{ include "local.labels" . | indent 2 }}
    app.kubernetes.io/component: {{ .Values.name }}-controller
  name: {{ .Values.name }}-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.name }}-controller
  template:
    metadata:
{{ include "local.labels" . | indent 6 }}
        app.kubernetes.io/component: {{ .Values.name }}-controller
    spec:
      containers:
      - name: csi-provisioner
        args:
        - --csi-address=$(ADDRESS)
        - --volume-name-prefix={{ .Values.agent.volume_name_prefix }}
        - --feature-gates=Topology=True
        - --strict-topology=True
        - --extra-create-metadata=true
        - --timeout=10m
        env:
        - name: ADDRESS
          value: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}/csi.sock
        - name: TZ
          value: Asia/Shanghai
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.provisioner.image }}:{{ .Values.images.provisioner.tag }}
        imagePullPolicy: {{ .Values.global.ImagePullPolicy }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
          name: socket-dir
      - name: csi-resizer
        args:
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}/csi.sock
        - name: TZ
          value: Asia/Shanghai
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.resizer.image }}:{{ .Values.images.resizer.tag }}
        imagePullPolicy: {{ .Values.global.ImagePullPolicy }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
          name: socket-dir
      - name: csi-snapshotter
        args:
        - --csi-address=$(ADDRESS)
        - --snapshot-name-prefix=snap
        env:
        - name: ADDRESS
          value: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}/csi.sock
        - name: TZ
          value: Asia/Shanghai
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.snapshotter.image }}:{{ .Values.images.snapshotter.tag }}
        imagePullPolicy: {{ .Values.global.ImagePullPolicy }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
          name: socket-dir
{{- if eq .Values.agent.driverMode "node" }}
      - name: csi-plugin
        args:
        - csi
        - --endpoint=$(CSI_ENDPOINT)
        - --nodeID=$(KUBE_NODE_NAME)
        - --driver={{ .Values.driver }}
        - --driver-mode=controller
{{- if .Values.controller.framework_scheduler_names }}
        - --framework-scheduler-names={{ .Values.controller.framework_scheduler_names }}
{{- end }}
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:/{{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}/csi.sock
        - name: TZ
          value: Asia/Shanghai
        - name: ISSUE_ORPHANED_POD
          value: "true"
        - name: ISSUE_BLOCK_REFERENCE
          value: "true"
        - name: ISSUE_MESSAGE_FILE
          value: "true"
{{- if .Values.global.YodaSchedulerSvcIP }}
        - name: EXTENDER_SVC_IP
          value: "{{ .Values.global.YodaSchedulerSvcIP }}"
{{- end }}
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.local.image }}:{{ .Values.images.local.tag }}
        imagePullPolicy: {{ .Values.global.ImagePullPolicy }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
          name: socket-dir
{{- end }}
      - name: controller
        args:
        - controller
        - --initconfig={{ .Values.name }}
        - --feature-gates=UpdateNLS={{ .Values.controller.update_nls }}
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.local.image }}:{{ .Values.images.local.tag }}
        imagePullPolicy: {{ .Values.global.ImagePullPolicy }}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        env:
        - name: TZ
          value: Asia/Shanghai
      - name: snapshot-controller
        image: {{ .Values.global.RegistryURL }}/{{ .Values.images.snapshot_controller.image }}:{{ .Values.images.snapshot_controller.tag }}
        env:
          - name: TZ
            value: Asia/Shanghai
        imagePullPolicy: {{ .Values.global.ImagePullPolicy }}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      serviceAccount: {{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      volumes:
{{- if eq .Values.agent.driverMode "node" }}
      - emptyDir: {}
        name: socket-dir
{{- else }}
      - name: socket-dir
        hostPath:
          path: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
          type: DirectoryOrCreate
{{- end }}
