kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}-csi-resizer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-csi-resizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Values.name }}-csi-resizer
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Values.name }}-csi-resizer
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      priorityClassName: system-cluster-critical
      serviceAccount: {{ .Values.name }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-resizer
          image: {{ .Values.globalconfig.RegistryURL }}/{{ .Values.images.resizer.image }}:{{ .Values.images.resizer.tag }}
          args:
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/{{ .Values.driver }}/csi.sock
            - name: TZ
              value: Asia/Shanghai
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/{{ .Values.driver }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.agent.kubelet_dir }}/plugins/{{ .Values.driver }}
            type: DirectoryOrCreate