apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-scheduler-extender
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-scheduler-extender
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Values.name }}-scheduler-extender
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Values.name }}-scheduler-extender
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: system-cluster-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.name }}-scheduler-extender
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - scheduler
        - --port={{ .Values.extender.port }}
        - --scheduler-strategy={{ .Values.extender.strategy }}
        image: {{ .Values.globalconfig.RegistryURL }}/{{ .Values.images.local.image }}:{{ .Values.images.local.tag }}
        imagePullPolicy: Always
        name: {{ .Values.name }}-scheduler-extender
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
        - name: TZ
          value: Asia/Shanghai
      serviceAccount: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-scheduler-extender
  name: {{ .Values.name }}-scheduler-extender
  namespace: {{ .Values.namespace }}
spec:
{{- if .Values.globalconfig.YodaSchedulerSvcIP }}
  clusterIP: {{ .Values.globalconfig.YodaSchedulerSvcIP }}
{{- end }}
  selector:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-scheduler-extender
  ports:
  - protocol: TCP
    port: {{ .Values.extender.port }}
    targetPort: {{ .Values.extender.port }}
    name: http-port