kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}-snapshot-controller
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    component: {{ .Values.name }}-snapshot-controller
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Values.name }}-snapshot-controller
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Values.name }}-snapshot-controller
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
        key: node-role.kubernetes.io/master
      priorityClassName: system-cluster-critical
      serviceAccount: {{ .Values.name }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: csi-snapshotter
          image: {{ .Values.globalconfig.RegistryURL }}/{{ .Values.images.snapshot_controller.image }}:{{ .Values.images.snapshot_controller.tag }}
          env:
            - name: TZ
              value: Asia/Shanghai
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
